import type { Metadata } from "next";
import { Vazirmatn, Geist } from "next/font/google";
import "./globals.css";
import ReactQuery from "@/lib/providers/ReactQuery";
import { cn } from "@/lib/utils";
import { ToastContainer } from 'react-toastify';
import Header from "@/component/layout/Header";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const font = Vazirmatn({
  variable: '--vazirmatn',
  subsets: ["arabic"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl" className={cn("font-sans", geist.variable)}>
      <body
        className={`${font.className} antialiased`}
      >
        <ToastContainer limit={1} />
        <ReactQuery>
          <Header />
          {children}
        </ReactQuery>
      </body>
    </html>
  );
}
